baseURL = 'https://notreallypk.github.io/'
languageCode = 'en-us'
title = 'Pratik Kokil'

[params]
  description = "Personal website of Pratik Kokil"

[markup.goldmark.renderer]
  unsafe = true  # Allows HTML in markdown

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/writings/"
    weight = 3
  [[menu.main]]
    name = "Tech"
    url = "/notes/"
    weight = 4
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 5
  [[menu.main]]
    name = "Reading"
    url = "/reading/"
    weight = 6
  # ... other menu items

[permalinks]
  about = "/:filename/"
  notes = "/notes/:filename/"
  writings = "/writings/:filename/"
  projects = "/projects/:filename/"